# Generated by Django 2.2.1 on 2019-09-24 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
